name: Deploy

on:
  push:
    branches: [ main ]    # main 브랜치에 push 시 실행

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # JDK Setup
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

        # Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Gradle을 통해 프로젝트를 빌드한다
      - name: Build Project
        run: ./gradlew clean build

        # 하위 디렉토리 생성
      - name: Make Directory
        run: mkdir deploy

        # JAR 파일 복사
      - name: Copy Jar File
        run: cp ./build/libs/*.jar ./deploy/

        # JAR 디렉토리 -> ZIP
      - name: Zip Directory
        run: zip -r -qq -j ./jar.zip ./deploy

        # S3 Bucket으로 업로드
      - name: Upload Zip File to S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./jar.zip s3://springboot-project/